// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhturebzahqmxjjvytju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVodHVyZWJ6YWhxbXhqanZ5dGp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDMxMzUsImV4cCI6MjA2NTY3OTEzNX0.NMwKFt7GjavOVo6UnDiiBwOZiTYRhK-RYo00OdCbBtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);